services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    ports:
      - port: 8000
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    mounts:
      - path: /app
        volume: api_data

  - type: web
    name: my-mysql-service
    env: docker
    plan: free
    dockerCommand: mysql:5.7
    mounts:
      - path: /var/lib/mysql
        volume: mq_data
