databases:
  - name: my-mysql-service
    databaseName: mydatabase
    user: myuser
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
services:
  - type: web
    name: app
    runtime: docker
    repo: https://github.com/odoh-tc/file_uploader
    plan: free
    envVars:
      - key: MYSQL_USER
        value: myuser
      - key: MYSQL_PASSWORD
        value: mypassword
      - key: MYSQL_ROOT_PASSWORD
        value: my-secret-pw
      - key: MYSQL_HOST
        value: db
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DB_NAME
        value: mydatabase
      - key: MYSQL_TEST_DB_NAME
        value: test_mydatabase
      - key: TESTING
        value: "false"
      - key: SECRET_KEY
        value: 61102c8a034548ebd7ed5990626e2435aeff8c68
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: BASE_URL
        value: http://localhost:8000
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
