services:
  - type: web
    name: app
    env: docker
    plan: free
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    dockerfilePath: ./Dockerfile

  - type: web
    name: my-mysql-service
    env: docker
    plan: free
    dockerCommand: mysql:5.7
