services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      MYSQL_USER: { fromFile: .env }
      MYSQL_PASSWORD: { fromFile: .env }
      MYSQL_DB_NAME: { fromFile: .env }
      MYSQL_HOST: my-mysql-service

  - type: web
    name: my-mysql-service
    env: docker
    plan: free
    dockerCommand: mysql:5.7
    envVars:
      MYSQL_USER: { fromFile: .env }
      MYSQL_PASSWORD: { fromFile: .env }
      MYSQL_DB_NAME: { fromFile: .env }
