services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile

  - type: web
    name: my-mysql-service
    env: docker
    plan: free
    dockerCommand: mysql:5.7
