services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    ports:
      - port: 8000
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

  - type: web
    name: my-mysql-service
    env: docker
    plan: free
    dockerCommand: mysql:5.7
